### PR TITLE
TUnit Support

### PR DESCRIPTION
**Pull request by thomhurst**
Support TUnit testing framework

### CODE REVIEW

**Comment by michaelstaib** [comment]
We are looking into it for new test projects

**Comment by michaelstaib** [comment]
Thank you for your contribution and sorry for the wait. I will ping the team to review this one over the next week and get it merged.

**Review by nscheibe — APPROVED** [review]
Well done, thank you very much

**Comment by nscheibe** [comment]
Hi @thomhurst, the review is done. Thanks a lot for your contribution, its highly appreciated.

**Comment by thomhurst** [comment]
Anything else need to be done? Azure pipelines doesn't want to run

**Comment by thomhurst** [comment]
😅

**Comment by SbiCA** [comment]
@michaelstaib @nscheibe  seems the pipeline is not running, I remember ages ago we had a similar issue is this related to being a new contributor (https://github.com/SwissLife-OSS/snapshooter/pull/119) ?

**Pull request merged**
