### PR TITLE
Allow customization of snapshot serializer settings

### PR DESCRIPTION
**Pull request by SbiCA**
Extract Json serialzation and resolving settings into own classes that are injected in the snapshot serializer (default implementation). By default the GlobalSnapshotSettingsResolver will look for all classes inheriting from SnapshotSerializerSettings and defining a default constructor and produce an ordered list with the active ones.  

Addresses #117

### CODE REVIEW

**Comment by SbiCA** [comment]
the build is failing due to sonar authentication not sure if @nscheibe @michaelstaib could help me there 🤔

**Comment by nscheibe** [comment]
Many thanks Simon for your contribution. I will review it this Friday morning and merge it into the master.

**Comment by nscheibe** [comment]
Hi Simon, I just checked your Pull Request now and I have to discuss your solution with the team, because I had another idea how to configure the JsonSerializerSettings without resolving the inherited SnapshotSerializerSettings.

My proposal is to create two ways to configure the SnapshotSerializerSettings:
1. Configuration via a static method (for global settings of the entire project):
```
public static class Snapshot
{
    public static ConfigureSerializer(Action<JsonSerializerSettings> jsonSerializerSettings)
    {
        ...
    }
}

Snapshot.ConfigureSerializer(serializer => 
	serializer.Culture = CultureInfo.InvariantCulture);
	
Snapshot.ConfigureSerializer(serializer => 
{
	serializer.Culture = CultureInfo.InvariantCulture;
	ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
});
```

2. Configuration via MatchOptions method (for local setting of one snapshot only):

```
public class MatchOptions
{
    ConfigureSerializer(Action<JsonSerializerSettings> jsonSerializerSettings)
    {
        ...
    }
}

Snapshot.Match(testPerson, matchOptions => matchOptions.ConfigureSerializer(serializer => 
	serializer.Culture = CultureInfo.InvariantCulture));
```

What do you think?

**Comment by nscheibe** [comment]
Hey guys, I need a bit your help for a decision :) @joslat @michaelstaib @philbir

**Comment by joslat** [comment]
> Hey guys, I need a bit your help for a decision :) @joslat @michaelstaib @philbir

Hi @nscheibe, I like your solution. You set up it in global and override as needed. Also, as you say, it goes with ASP.NET style too ;)
Hi @SbiCA! Nice to see you here :)

**Comment by SbiCA** [comment]
@nscheibe @joslat I agree that this would be the asp.net-ism but there are two problems I see with such approach **1**
- It's not clear if you want it to be a global configuration e.g. you'll still need a base class in the test project
``` c#
public class MyGlobalSettings 
{
     public MyGlobalSettings()
     {
         // since this will be set for all tests anyway
          Snapshot.ConfigureSerializer(serializer => 
          {
	          serializer.Culture = CultureInfo.InvariantCulture;
	          ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
          });
    }
}

public class MyRealTest : MyGlobalSettings
{

   [Fact]
    public void MyTest()
  {
        ...
  }

}

````
- I've actually implemented this approach and in order to have tests in `Snapshooter` you can not isolate the behaviour e.g. It'll break other tests that rely on certain serializer behaviour (Because the backing field will be static e.g. loaded once per Test-run for the entire-Project and there for breaking `Enum` serialization behaviour) . hence this was the reason I came up with `Active` + `Order` so you could even override/enhance behaviour defined by a base class or library. In ASP.NET this usually works because you're running a single host application that constructs those kind of dependencies via a `Builder`-Pattern (that's why `ISnapshotSettingsResolver` was introduced 😄 )

I think approach **2** is a fine extension that allows certain local behaviour and testability is given since you passing in the backing `Settings`

So in IMHO I guess we can go for 1) if there is clear docs but I guess it's not as clear as having a dedicate class just for this purpose and additionally having a configuration class would allow loading it from `appsettings.json` or `snapshooter.json` in the future ... so you wouldn't even need code in order to change the snapshooter behaviour 🥰

**Comment by joslat** [comment]
@SbiCA that's true. Stand on Simon's suggestion. 
@nscheibe :) ?

**Comment by nscheibe** [comment]
@SbiCA Ok, you are right.  :)

**Review by nscheibe — APPROVED** [review]
Well done!

**Comment by SbiCA** [comment]
@nscheibe Thanks for the review is there any action left from my side? 
I somehow think you'll need to skip the `cla` part because I signed it with my github user but use a different name in the comment therefore the extension seems to be stating `simi` didn't sign the CLA.

**Comment by nscheibe** [comment]
@glucaci I am sorry to bother you again.... :)

**Comment by glucaci** [comment]
0.6.0 is on the way which includes this PR

**Pull request merged**
