### PR TITLE
MSTest support

### PR DESCRIPTION
**Pull request by aaronpowell**
## Summary

Implemented support for MS Test as a testing framework.

This added a new project (and thus, NuGet package) which contains the MS Test specific logic.

Much of the logic is copied from the Xunit implementation, but with a custom implementation of the snapshot name generator, as there seems to be no way to know the params that were provided using the `DataRow` attribute at runtime, so instead there's a dictionary that is used as a lookup point to track the iterations of a data-drive test.

Addresses #139

### CODE REVIEW

**Review by nscheibe — APPROVED** [review]
Very nice! Well done! Thx a lot.

**Review by nscheibe — APPROVED** [review]

**Comment by nscheibe** [comment]
@aaronpowell just sign the Swiss Life OSS cla, then I am allowed to merge it to master :)

**Comment by aaronpowell** [comment]
> @aaronpowell just sign the Swiss Life OSS cla, then I am allowed to merge it to master :)

Done

**Comment by aaronpowell** [comment]
Woo! Let me know when there's a nuget package I can test against

**Pull request merged**
